name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 1.0.3
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.1.6
  http: ^0.13.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
